[package]
name = "diceware"
version = "1.0.1"
license = "GPL-3.0"
authors = ["Jean-Philippe Cugnet <jean-philippe@cugnet.eu>"]

[dependencies]
clap = "~2.31.0"
rand = "0.5.0"
unicode-segmentation = "1.2.0"

[dev-dependencies]
proptest = "0.7.0"
